module.exports = {
    getLinks: async (page) => {
        let links = await page.evaluate(_ => {
        let urlChecker = new RegExp("^(http://www.|https://www.|http://|https://)?[a-z0-9]+([-.]{1}[a-z0-9]+)*.[a-z]{2,5}(:[0-9]{1,5})?(/.*)?$");
        let links = makeArrayFromDocument("a")
            .filter(x => x.href.match(urlChecker)) // Get rid of non-links...
            .map(x => new URL(x.href.split("#")[0].split("?")[0])) // Clean URLS of query strings and hashes...
            .filter(x => !x.href.endsWith('pdf')) // Remove PDFs...
            .filter(x => x.host === new URL(window.location.href).host) // Hosts must match...
            .filter(x => x.pathname !== window.location.pathname) // But not the actual path...
            .reduce((agg, item) => agg.some(x => x.href === item.href) ? agg : [ ...agg, item ], []); // Remove any duplicates from this page...
        return JSON.stringify(links);
        });
        return links;
    }
};